IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'ControlAcceso')
BEGIN
    CREATE DATABASE ControlAcceso;
END
GO

USE ControlAcceso;
GO

ALTER DATABASE ControlAcceso SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE ControlAcceso SET READ_COMMITTED_SNAPSHOT ON;
GO
